### ISSUE TITLE
TODO list - ideas for improvements

### ISSUE THREAD

**Issue by heathhenley** [heathhenley/Shipwrecks#1]
Some improvement ideas:
- [x] panel or overlay with information / link to this Github / etc 
- [x] some wrecks have no data references, can we fix that?
- [x] add sonar data layers to map
  - [x] FarSounder (http://static.farsounder.com/narragansett_bay_overview/)
  - [x] NOAA Bag (https://noaa.maps.arcgis.com/home/webmap/viewer.html?layers=7ca0a68d6fd8480cb83c89173ab9d814)
- [x] display on mobile is a little small
- [x] toggle wreck markers (default on) --> when you zoom in a lot, could be cool to be able to look at bathy without the marker in the way
- [x] refactor template a bit - it's pretty messy
- [ ] make the pop up a little prettier (bootstrap "note" for the data notice", maybe a table or card for the the rest) 
- [ ] migrate sqlite database to postgres
- [ ] use django to write api to return data in json: 
  - [ ] list all
  - [ ] all within radius of lat/lon
  - [ ] all between given years
- [ ] allow 'report problem / suggest edit' 
- [ ] add log in / auth
- [ ] add wreck detail view - allow commenting?
